name: RandomTeleport
version: @version@
main: black.bracken.randomteleport.RandomTeleport
authors: []
api-version: 1.18

commands:
  randomteleport:
    aliases: [rtp]
    permission: randomteleport.use

permissions:
  randomteleport.*:
    children:
      randomteleport.use: true
  randomteleport.use:
    default: true
